language: python

python:
  - "3.7"

env:
  - DJANGO_VERSION=3.0.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

services:
  - redis

script:
  - py.test --cov=social_network social_network/tests

after_success:
  - codecov